name: lerobot-migraphx
channels:
  - robostack-staging
  - conda-forge
dependencies:
  - python=3.10
  - cxx-compiler
  - libstdcxx-ng # for xensevr_pc_service_sdk
  - cmake
  - ninja
  - eigen
  - boost
  - spdlog
  - pybind11
  - wheel
  - click
  - pyzmq
  - pynput
  - pip
  - evdev
  - wxpython # for pico4
  # NOTE: You need to install AMD Unified Driver Package Repositories and Installer Script
  # wget https://repo.radeon.com/amdgpu-install/7.1.1/ubuntu/noble/amdgpu-install_7.1.1.70101-1_all.deb
  # sudo apt install ./amdgpu-install_7.1.1.70101-1_all.deb
  - conda-forge::ffmpeg=7.1.1 # for libsvtav1 encoder
  - conda-forge::soem=1.4.0 # This package is missing in aarch64
  # `git clone https://github.com/OpenEtherCATsociety/SOEM.git && cd SOEM`
  # `mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX .. && make -j && make install`
